### PR TITLE
Create GitHub Action for build automation

### PR DESCRIPTION
**Pull request by 0blu**
Testing if all configurations can be build
and creates artifacts (example: https://github.com/0blu/WoW-Launcher/actions/runs/3389924426)

Would be cool if the `static-auth-seed` could be merged too (_toggled by Configuration_).

### CODE REVIEW

**Comment by Fabi** [comment]
Thank you! I might consider adding a build pipeline with the new code sign cert and directly to through azure pipelines. 

for the static auth seed it might be possible to merge yea. I’m not sure if it should be done through new build configs or a command line switch yet.

**Comment by 0blu** [comment]
GitHub Actions has the advantage that it is freely available, easy to change and already setup when you fork the project.

If you want to create a signed build I can create a release action that [signs the build](https://archi-lab.net/code-signing-assemblies-with-github-actions/) (your certificate would be stored in a private variable, just for the `main` branch).

You could also consider using the azure pipeline just for the release build and signing, but this would mean a redundant configuration.

**Comment by Fabi** [comment]
> GitHub Actions has the advantage that it is freely available, easy to change and already setup when you fork the project.
> 
> If you want to create a signed build I can create a release action that [signs the build](https://archi-lab.net/code-signing-assemblies-with-github-actions/) (your certificate would be stored in a private variable, just for the `main` branch).
> 
> You could also consider using the azure pipeline just for the release build and signing, but this would mean a redundant configuration.

github actions are actually kind of backed by azure pipelines. they use the same build machines. i just don’t like the way how github action configs work. i prefer to do it on my azure dashboard and their yaml

**Comment by Fabi** [comment]
> Testing if all configurations can be build and creates artifacts (example: https://github.com/0blu/WoW-Launcher/actions/runs/3389924426)
> 
> Would be cool if the `static-auth-seed` could be merged too (_toggled by Configuration_).

Merged the branch into the windows branch and added a --staticseed arg. Also created new releases

Might add a configuration for it later but I don't see any need for it atm.

**Pull request closed without merging**
